spring:
  autoconfigure:
    exclude: 
      - org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration
  datasource:
    url: jdbc:postgresql://postgres-db:5432/rideswift
    username: admin
    password: secret
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false      

server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
